# permissions for end users to view appservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appserver-viewer-role
rules:
- apiGroups:
  - app-group.book.asppj.top
  resources:
  - appservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app-group.book.asppj.top
  resources:
  - appservers/status
  verbs:
  - get
